### ISSUE TITLE
"<closeTab/>" action doesn't close chrome "print" system window 

### ISSUE THREAD

**Issue by 1408sheva** [magento/magento2-functional-testing-framework#133]
If system window chrome "print" is opened, then we can not to do anything, even close Tab, and do not perform another action (go to the page, click ...)

### Preconditions

1. Browser Chrome

### Steps to reproduce

1. Create order on StoreFront
2. Click *Print Receipt* button
3. System window chrome "print" is opened

### Expected result

1. `<closeTab` `stepKey="close"/>`  - should close the tab

### Actual result

1. [Logs, Errors]
`<closeTab` `stepKey="close"/>`  - does not close the tab

**Comment by magterskine** [comment]
This ticket is unable to be completed. Print dialogs are considered system dialogs and drivers are unable to interact with them.
A workaround for this is, rather than clicking the print button, make an assertion that the print button has the correct javascript function that would cause a print dialog to open.
