### ISSUE TITLE
A possible conditional ActionGroup?

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2-functional-testing-framework#504]
### Steps to reproduce
Have an alternative flow in the test. maybe a popup is shown only in a certain scenario which isn't predictable enough to dedicate a test to itself. For example, if a conditional click is executed since an element is visible, but maybe an extra action _other than a click_ is required to perform **when** the conditional click is true and executed; maybe an extra modal needs to be closed, etc.

### Expected result
Currently, only a [conditional click](https://devdocs.magento.com/mftf/docs/test/actions.html#conditionalclick) is available. I think adding a conditional ActionGroup, would cover any conditional scenarios such that the ActionGroup itself executes only if the condition is true (existing selector visibility condition can be used). This would help us queue actions based on an element's visibility and **not just** a click. 

In simple words, every action can be made conditional when put inside a conditional ActionGroup.

### Actual result
Cannot queue actions based on a conditional click

**Comment by KevinBKozan** [comment]
@drpayyne we've had long discussions internally on this, and we've generally come to the conclusion that this kind of conditional actionGroup doesn't line up with the paradigm of `deterministic test`.
We cut it off at conditional click since it's very clear cut, like if a popup comes up that is based on something like caching, but it doesn't alter the workflow of the test as much as a whole actionGroup could.
